### DISCUSSION TITLE
Flow name uniqueness

### DISCUSSION THREAD

**Discussion by ribalba** [green-coding-solutions/green-metrics-tool#1149] [Ideas]
Flow names need to be unique. Which sort of makes sense from a ui perspective as you don't want flow steps called A, A, A but what I often have is 
```
  - sleep: sleep
    name: sleep
    container: bench-service
    commands:
      - type: console
        command: sleep 10
```

because the name needs to be unique I keep adding junk to the name. So 
```
name: sleepASDASDASDASDASD
```

which isn't very nice. Also I would love to do something like 
```
sleep: &sleep
  name: sleep
  container: test-service
  commands:
    - type: console
      command: sleep 10

flow:

  - *sleep
```
for things that repeat. 

I get why names should be unique but do we really want to enforce this? If so, maybe we can add some sort of standard that overrides this.
