### ISSUE TITLE
Refactor the runner.py to load metric providers with parameters

### ISSUE THREAD

**Issue by ribalba** [green-coding-solutions/green-metrics-tool#39]
Currently if we want to monitor two fans in a system we need to create two separate metric providers. This could be streamlined by allowing metric providers to take parameters. I suggest to following refactor to the `config.yml` and systems that consume such. 

```
measurement:
  metric-providers:
    lm_sensors.temperature.cpu.provider.LmSenorsCpuTempProvider: 100
    lm_sensors.fan.1.provider.FanOneProvider: 100
    lm_sensors.fan.2.provider.FanTwoProvider: 100
```
this is how it looks currently which is very verbose and has loads of code duplication on the metric side of things. 

```
measurement:
  metric-providers:
    (lm_sensors.provider.LmSenorsProvider, 100, 'CPU', 'cpu_temp', 100, 'C', 'show_graph')
    (lm_sensors.provider.LmSenorsProvider, 100, 'fan1', 'fan1_temp, 1, 'RPM', 'show_graph')
    (lm_sensors.provider.LmSenorsProvider, 100, 'fan2, 'fan2_temp, 1, 'RPM', 'show_avg')
```

This enables us to also render the metrics in the front end dynamically as all information is in the config. Also we could change the underlying `metric-provider-binary` to consume multiple configurations so we only need to run one instance that outputs multiple values. 

This can also make it quite easy to measure the temperature of each core for example. Which currently would need the number of cores providers running.
