### ISSUE TITLE
depends_on uses wrong name

### ISSUE THREAD

**Issue by ribalba** [green-coding-solutions/green-metrics-tool#871]
This will fail:
```
services:
  nginx:
    image: nginx:latest
    container_name: nginx_https

  curl:
    build:
      context: .
      dockerfile: curl.Dockerfile
    container_name: curl_client
    depends_on:
      - nginx
```

As docker compose wants the key, hence `nginx` but we use `dependent_container_name` so `nginx_https`

https://github.com/green-coding-solutions/green-metrics-tool/blob/81c3ff9fd51f36af68424973d2ee41209864ec67/runner.py#L906

Error can be found here:

https://metrics.green-coding.io/stats.html?id=d6e03f31-0dab-47da-81a5-cede40bcb7a8
